[book]
authors = ["Mike Zhang Zhi"]
language = "zh_cn"
multilingual = false
src = "src"
title = "Arduino Uno Rust开发实战"

[rust]
edition = "2021"

[output.html]
default-theme = "rust"
mathjax-support = true
git-repository-url = "https://github.com/snowwolf007cn/arduino-rust-book.git"
git-repository-icon = "fa-github"

[output.html.playground]
runnable = false

[preprocessor.image-size]
command = "mdbook-image-size"
