[book]
authors = ["Mike Zhang Zhi"]
language = "zh_cn"
multilingual = false
src = "src"
title = "Arduino Uno Rust开发实战"

[rust]
edition="2021"

[output.html.playground]
runnable = false

[preprocessor.image-size]
command = "mdbook-image-size"
